-- SET pig.splitCombination false
-- SET mapred.min.split.size 104857600
-- SET mapreduce.input.fileinputformat.split.maxsize 4294967296
SET mapreduce.input.fileinputformat.split.minsize 104857600
generated = LOAD '$src/$srcfile' 
    USING PigStorage(',' , '-noschema')
    AS (line: int, gaussian: double, b: boolean, c:chararray );
sorted = ORDER generated BY c ASC;
f = FILTER sorted BY gaussian >= 0;
result = f;
STORE result INTO  '$dest/$destdir';
