-- SET pig.splitCombination false
-- SET mapred.min.split.size 65536
generated = LOAD '$src/$srcfile' 
    USING PigStorage(',' , '-noschema')
    AS (line: int, gaussian: double, b: boolean, c:chararray );
sorted = ORDER generated BY c ASC;
f = FILTER sorted BY gaussian >= 0;
result = f;
STORE result INTO  '$dest/$destdir';
